Improvements to test v2
abap-openapi/abap-openapi pull request #92
Opened 2023-01-15 14:16 UTC by gregorwolf

- Node.JS cli for v2 generation
- ABAP report to test v2 generation

2023-01-17 12:33 UTC, larshp commented
set `selectionScreenBlockIndentation` in the abaplint configuration for https://rules.abaplint.org/indentation/

2023-01-17 12:36 UTC, larshp commented
https://github.com/abaplint/abaplint/issues/2846 opened

2023-01-17 12:42 UTC, larshp requested changes

2023-01-17 12:42 UTC, larshp commented on test_v2/index.mjs
> +  );
suggest some refactoring here, its the same code as in https://github.com/abap-openapi/abap-openapi/blob/main/test_v2/test.mjs#L23

I'll forget changing the index file if its not used in tests

2023-02-19 10:52 UTC, colbyhemond commented
@gregorwolf I was trying out the ABAP program you've added with the malware spec you linked in the original comment. 

I found that if the description fields are too long then it was causing a short dump in the `cl_sxml_string_reader`. I had also attempted to read the JSON spec with `/ui5/cl_json_parser` which resulted in the same issues.

After I reduced the length of the descriptions, it generated like the web client.

* It seems like the manual work around is to reduce the length of the description texts in the JSON specs. 
* TO fix the root of the issue it seems we need to use a different class to read in the JSON spec. -- @gregorwolf or @larshp are you aware of a different class that could read in the JSON file that won't dump because of a value being to long?

2023-02-21 17:37 UTC, colbyhemond commented
@gregorwolf after looking into it further it appears the `SOTR_SERV_TABLE_TO_STRING` FM was causing the 255 character restriction that was causing the long descriptions to short dump. In my local copy I replaced it with the code below and it appears to not cause any issues with the schemas I've been testing with.
```abap
DATA json_string TYPE string.
LOOP AT data_tab ASSIGNING FIELD-SYMBOL(<wa>).
    json_string = json_string && <wa>.
ENDLOOP.
```

2024-03-21 15:13 UTC, larshp commented
closing, feel free to open new PR which passes CI

2024-03-21 15:13 UTC, closed without merging